// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWAfm2J_c-x0Q259qtSqshAu1OSuRdmcY',
    appId: '1:1085708993796:web:20f237bfaf50fb31eafc51',
    messagingSenderId: '1085708993796',
    projectId: 'canvas-elec',
    authDomain: 'canvas-elec.firebaseapp.com',
    storageBucket: 'canvas-elec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRofN9xSGc-YEzQVqk6MJ1qQlNr5oySNA',
    appId: '1:1085708993796:android:68827c8bcd394ae8eafc51',
    messagingSenderId: '1085708993796',
    projectId: 'canvas-elec',
    storageBucket: 'canvas-elec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdj-24sM6gDoesIbl2T2nImcmeUA_AIPo',
    appId: '1:1085708993796:ios:70d1918b73729817eafc51',
    messagingSenderId: '1085708993796',
    projectId: 'canvas-elec',
    storageBucket: 'canvas-elec.firebasestorage.app',
    iosBundleId: 'com.electream.canvas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdj-24sM6gDoesIbl2T2nImcmeUA_AIPo',
    appId: '1:1085708993796:ios:70d1918b73729817eafc51',
    messagingSenderId: '1085708993796',
    projectId: 'canvas-elec',
    storageBucket: 'canvas-elec.firebasestorage.app',
    iosBundleId: 'com.electream.canvas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWAfm2J_c-x0Q259qtSqshAu1OSuRdmcY',
    appId: '1:1085708993796:web:953227d2f5a7265aeafc51',
    messagingSenderId: '1085708993796',
    projectId: 'canvas-elec',
    authDomain: 'canvas-elec.firebaseapp.com',
    storageBucket: 'canvas-elec.firebasestorage.app',
  );
}
